FROM python:3.12.12-slim-bookworm

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir uv

RUN apt-get update \
    && apt-get upgrade -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml README.md ./
COPY src ./src

RUN uv pip install --system -e .

EXPOSE 8000

CMD ["uvicorn", "early_sepsis.serving.api:app", "--host", "0.0.0.0", "--port", "8000"]
