from __future__ import annotations

# ruff: noqa: E402
import argparse
import json
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from early_sepsis.modeling.experiment_analysis import (
    aggregate_sequence_experiments,
    build_model_manifest_from_row,
    select_best_run,
)
from early_sepsis.modeling.model_manifest import save_model_manifest


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Select best sequence checkpoint and persist model manifest"
    )
    parser.add_argument(
        "--model-root", default="artifacts/models", help="Root directory for model artifacts"
    )
    parser.add_argument(
        "--comparison-csv",
        default=None,
        help="Optional existing comparison CSV generated by compare_experiments.py",
    )
    parser.add_argument(
        "--selection-metric",
        default="validation_auprc",
        help="Metric column used for selecting the best run",
    )
    parser.add_argument(
        "--dataset-tag",
        default=None,
        help="Optional dataset tag filter (e.g., physionet or kaggle_csv)",
    )
    parser.add_argument(
        "--manifest-path",
        default="artifacts/models/registry/selected_model.json",
        help="Output JSON manifest path",
    )
    return parser


def _load_frame(args: argparse.Namespace) -> pd.DataFrame:
    if args.comparison_csv:
        comparison_path = Path(args.comparison_csv)
        if not comparison_path.exists():
            msg = f"Comparison CSV not found: {comparison_path}"
            raise FileNotFoundError(msg)
        return pd.read_csv(comparison_path)

    return aggregate_sequence_experiments(model_root=args.model_root, project_root=PROJECT_ROOT)


def main() -> None:
    args = _build_parser().parse_args()

    frame = _load_frame(args)
    best_row = select_best_run(
        frame,
        selection_metric=args.selection_metric,
        dataset_tag=args.dataset_tag,
    )

    manifest = build_model_manifest_from_row(
        best_row,
        project_root=PROJECT_ROOT,
        selection_metric=args.selection_metric,
    )

    resolved_manifest_path = save_model_manifest(args.manifest_path, manifest)

    payload = {
        "manifest_path": str(resolved_manifest_path),
        "selection_metric": args.selection_metric,
        "selected_run": manifest["selected_run"],
        "dataset": {
            "dataset_tag": manifest["dataset"]["dataset_tag"],
            "windows_dir": manifest["dataset"]["windows_dir"],
        },
        "thresholds": manifest["thresholds"],
        "validation_auprc": float(manifest["metrics"]["validation"].get("auprc", 0.0)),
        "test_auprc": float(manifest["metrics"]["test"].get("auprc", 0.0)),
    }

    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
